import React from "react"

export default function Articles(){
    return(
        <section>
                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis quidem aliquam quo, illo vero quam adipisci optio, commodi hic magni assumenda aut, rem sed? Pariatur reprehenderit rerum accusantium aperiam, cupiditate recusandae earum deserunt ratione soluta at odio ullam quo. Optio natus consequatur itaque ab fuga temporibus officia, necessitatibus totam eos distinctio eum beatae, reiciendis rerum accusantium numquam provident quis iure, soluta repellendus ipsum quae. Expedita, accusamus vel similique iste exercitationem est at qui alias soluta autem iure, odit maiores, consectetur laboriosam! Esse dignissimos culpa tempora beatae aliquam rem velit consequuntur perferendis iure, ut aperiam labore cumque, harum dolorum tempore numquam, dolores laboriosam autem doloremque rerum eveniet adipisci! Explicabo sint, voluptatem commodi sequi quod enim, adipisci minus quasi autem vero fugiat similique praesentium amet atque officiis repudiandae dicta unde aperiam corporis reprehenderit quia! Illo fugit quam eum, explicabo rem molestiae ullam, molestias iste obcaecati harum perferendis itaque, vero expedita eos recusandae? Possimus, at? Fuga, iste adipisci non tempora et minima dolorum in veritatis officiis perspiciatis quibusdam dolorem amet, at corrupti esse vitae voluptatum est exercitationem earum? Odio omnis dolores velit dolore saepe ut, blanditiis nam nulla sapiente illum, asperiores laborum vel! Fuga molestias dolorum illo quos eveniet aliquam voluptatibus id facilis.</p>
                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis quidem aliquam quo, illo vero quam adipisci optio, commodi hic magni assumenda aut, rem sed? Pariatur reprehenderit rerum accusantium aperiam, cupiditate recusandae earum deserunt ratione soluta at odio ullam quo. Optio natus consequatur itaque ab fuga temporibus officia, necessitatibus totam eos distinctio eum beatae, reiciendis rerum accusantium numquam provident quis iure, soluta repellendus ipsum quae. Expedita, accusamus vel similique iste exercitationem est at qui alias soluta autem iure, odit maiores, consectetur laboriosam! Esse dignissimos culpa tempora beatae aliquam rem velit consequuntur perferendis iure, ut aperiam labore cumque, harum dolorum tempore numquam, dolores laboriosam autem doloremque rerum eveniet adipisci! Explicabo sint, voluptatem commodi sequi quod enim, adipisci minus quasi autem vero fugiat similique praesentium amet atque officiis repudiandae dicta unde aperiam corporis reprehenderit quia! Illo fugit quam eum, explicabo rem molestiae ullam, molestias iste obcaecati harum perferendis itaque, vero expedita eos recusandae? Possimus, at? Fuga, iste adipisci non tempora et minima dolorum in veritatis officiis perspiciatis quibusdam dolorem amet, at corrupti esse vitae voluptatum est exercitationem earum? Odio omnis dolores velit dolore saepe ut, blanditiis nam nulla sapiente illum, asperiores laborum vel! Fuga molestias dolorum illo quos eveniet aliquam voluptatibus id facilis.</p>
                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis quidem aliquam quo, illo vero quam adipisci optio, commodi hic magni assumenda aut, rem sed? Pariatur reprehenderit rerum accusantium aperiam, cupiditate recusandae earum deserunt ratione soluta at odio ullam quo. Optio natus consequatur itaque ab fuga temporibus officia, necessitatibus totam eos distinctio eum beatae, reiciendis rerum accusantium numquam provident quis iure, soluta repellendus ipsum quae. Expedita, accusamus vel similique iste exercitationem est at qui alias soluta autem iure, odit maiores, consectetur laboriosam! Esse dignissimos culpa tempora beatae aliquam rem velit consequuntur perferendis iure, ut aperiam labore cumque, harum dolorum tempore numquam, dolores laboriosam autem doloremque rerum eveniet adipisci! Explicabo sint, voluptatem commodi sequi quod enim, adipisci minus quasi autem vero fugiat similique praesentium amet atque officiis repudiandae dicta unde aperiam corporis reprehenderit quia! Illo fugit quam eum, explicabo rem molestiae ullam, molestias iste obcaecati harum perferendis itaque, vero expedita eos recusandae? Possimus, at? Fuga, iste adipisci non tempora et minima dolorum in veritatis officiis perspiciatis quibusdam dolorem amet, at corrupti esse vitae voluptatum est exercitationem earum? Odio omnis dolores velit dolore saepe ut, blanditiis nam nulla sapiente illum, asperiores laborum vel! Fuga molestias dolorum illo quos eveniet aliquam voluptatibus id facilis.</p>
                 </section>
    )
}