import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [count,setCount] =useState(0)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      
        <h1>Counter: {count}</h1>
        <button onClick={()=>setCount(count+1)}>increment</button>
      </main>

    </div>
  )
}
